### ISSUE TITLE
Request: Unleashed Blast Furnaces DP

### ISSUE THREAD

**Issue by ActualBest** [DMBuce/bucepack#2]
A datapack that unleashes the blast furnace's potential by allowing the player to blast cobble, sand, deepslate, bricks, and other "stoney" items at 2x the speed of regular smelting.

**Comment by DMBuce** [comment]
Interesting idea. Conceptually I'm not sure it makes complete sense, since blast furnaces are used in metallurgy to smelt metals (see link below). But I know it's a common request to add more blast furnace recipes, and after a quick search the most recent datapack with this feature that I could find is from 1.16. So I'll think about it.

https://en.wikipedia.org/wiki/Blast_furnace

**Comment by ActualBest** [comment]
Looks like this is added in the [Brick Oven](https://github.com/DMBuce/bucepack?tab=readme-ov-file#brick-oven) pack, but the [download link](https://github.com/DMBuce/bucepack/releases/latest/download/oven_brick.zip) doesn't seem to work.

Loving these packs by the way, thanks!

**Comment by DMBuce** [comment]
That datapack is new so there wasn't a download published for it yet. I just cut a new release so the download link should be working now.

Note that the stone recipes are added to the smoker and campfire, not the blast furnace as you originally requested. And to make the pack easier to maintain in the future, I wrote a script that copies modified versions of all non-blast-furnace, non-smoker recipes to the smoker and campfire. So it's an undocumented feature that you're also able to cook things like charcoal, popped chorus fruit, green dye, etc. It turns out that the list of these recipes is pretty short so I didn't feel it was worth the effort to filter them out, but I can always do that in the future if need be.

Glad to hear that you're enjoying my packs! It's always nice to receive positive feedback. :)

Have a good one
